{
    'name': 'Campus academic',
    'version': '19.0.1.0.0',
    'summary': 'Core Module for University ERP (SIAKAD)',
    'description': 'Master Facilities, Institutions, KRS Management, and Smart Scheduling.',
    'category': 'Education',
    'author': 'Hajril Malik',
    'depends': ['base', 'hr', 'mail', 'website'],
    'data': [
        'security/campus_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_activity_type_data.xml',
        'data/website_configurator_bypass.xml',
        'report/report_actions.xml',
        'report/report_krs_template.xml',
        'report/report_khs_template.xml',
        'report/report_transcript_template.xml',
        'wizard/krs_generator_wizard_views.xml',
        'wizard/assign_schedule_wizard_views.xml',
        'views/res_partner_views.xml',
        'views/campus_facility_views.xml',
        'views/academic_institution_views.xml',
        'views/academic_krs_views.xml',
        'views/academic_course_package_views.xml',
        'views/academic_khs_views.xml',
        'views/academic_class_views.xml',
        'views/academic_class_schedule_views.xml',
        'views/website_homepage_core.xml',
        'views/website_layout_core.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
